#!/bin/bash
alias help_git='     cat     ~/.cheatsheet/help_git'
alias help_tmux='    cat     ~/.cheatsheet/help_tmux'
alias help_tool='    cat     ~/.cheatsheet/help_tool'
alias help_vim='     cat     ~/.cheatsheet/help_vim'
alias help_waveform='cat     ~/.cheatsheet/help_waveform'
alias help_dabble='cat     ~/.cheatsheet/help_dabble'
alias help_slurm='cat     ~/.cheatsheet/help_slurm'
alias help_testplanner='cat  ~/.cheatsheet/help_testplanner'
alias help_server='cat  ~/.cheatsheet/help_server'

# AI Skill script
alias SKILL_run_plan_yaml.sh='~/.augment/skills/federation-build-run/scripts/run_plan_yaml.sh'
alias SKILL_setup_new_federation.sh='~/.augment/skills/federation-build-run/scripts/setup_new_federation.sh'
