#!/bin/bash

alias ll="ls -lh"
alias rd='readlink'
alias dirs='dirs -v'

# For SiFive Slurm fair share
export SALLOC_ACCOUNT=perf
export SLURM_ACCOUNT=perf
export SBATCH_ACCOUNT=perf
export SLURM_PARTITION=standard_scl,redhat
export SLURM_CONSTRAINT=perf_host
export SALLOC_CONSTRAINT=perf_host
export SBATCH_CONSTRAINT=perf_host
